#!/usr/bin/env bash
#
# Chord Theory Reference Card
#
# Generates a comprehensive music-theory reference for a curated set of
# chord types: major triad, minor triad, dominant 7th, diminished 7th,
# augmented triad, and minor-major 7th. For each chord this script
# produces:
#   1. Spelling (notes, PCs, intervals) via `spell --format all`
#   2. Naming verification via `name` (round-trip: PCs back to name)
#   3. Prime form and Forte number classification
#   4. Interval-class vector with labeled breakdown
#   5. Full interval matrix (text)
#   6. Pitch-circle SVG diagram
#   7. Interval-matrix SVG diagram
#
# This exercises the `spell`, `name`, `prime-form`, `forte`,
# `interval-vector`, `interval-matrix`, and `pitch-circle` subcommands
# in a unified reference workflow — the kind of material a music theory
# student would generate when studying set-class properties of common
# chord types.
#
# Output:
#   - Text report: examples/output/chord_theory_reference.txt
#   - SVG diagrams: examples/output/theory_ref_*.svg
#
# Usage:
#   bash slonimsky/examples/scripts/chord_theory_reference.sh
#   SLONIMSKY=/path/to/slonimsky bash slonimsky/examples/scripts/chord_theory_reference.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
OUT_DIR="$SCRIPT_DIR/../output"
mkdir -p "$OUT_DIR"

# Find binary
if [ -n "${SLONIMSKY:-}" ]; then
  S="$SLONIMSKY"
elif command -v slonimsky &>/dev/null; then
  S=slonimsky
else
  # Try workspace target dir
  for candidate in \
    "$SCRIPT_DIR/../../../target/debug/slonimsky" \
    "$SCRIPT_DIR/../../../target/release/slonimsky"; do
    if [ -x "$candidate" ]; then
      S="$candidate"
      break
    fi
  done
fi

if [ -z "${S:-}" ]; then
  echo "ERROR: slonimsky binary not found. Build with: cargo build -p slonimsky" >&2
  exit 1
fi

REPORT="$OUT_DIR/chord_theory_reference.txt"
: > "$REPORT"

header() {
  echo "" >> "$REPORT"
  echo "================================================================" >> "$REPORT"
  echo "  $1" >> "$REPORT"
  echo "================================================================" >> "$REPORT"
  echo "" >> "$REPORT"
}

section() {
  echo "--- $1 ---" >> "$REPORT"
}

# Chord definitions: symbol, PCs (space-separated), and a short slug for filenames
# Using PCs for chords where from_symbol may not support non-C roots
CHORDS=(
  "Cmaj|0 4 7|major_triad"
  "Cm|0 3 7|minor_triad"
  "C7|0 4 7 10|dom7"
  "Cdim7|0 3 6 9|dim7"
  "Caug|0 4 8|aug_triad"
  "CmMaj7|0 3 7 11|min_maj7"
)

echo "Chord Theory Reference Card" >> "$REPORT"
echo "Generated by slonimsky" >> "$REPORT"
echo "$(date -u +%Y-%m-%dT%H:%M:%SZ)" >> "$REPORT"

for entry in "${CHORDS[@]}"; do
  IFS='|' read -r symbol pcs slug <<< "$entry"

  header "$symbol  (PCs: $pcs)"

  # 1. Spell
  section "Spelling"
  $S spell "$symbol" --format all >> "$REPORT" 2>/dev/null || \
    echo "(spell not available for $symbol)" >> "$REPORT"
  echo "" >> "$REPORT"

  # 2. Name (round-trip from PCs)
  section "Name (from PCs)"
  # shellcheck disable=SC2086
  $S name $pcs >> "$REPORT" 2>/dev/null || \
    echo "(naming failed for PCs: $pcs)" >> "$REPORT"
  echo "" >> "$REPORT"

  # 3. Prime form
  section "Prime Form"
  # shellcheck disable=SC2086
  $S prime-form $pcs >> "$REPORT" 2>/dev/null
  echo "" >> "$REPORT"

  # 4. Forte number
  section "Forte Number"
  # shellcheck disable=SC2086
  $S forte $pcs >> "$REPORT" 2>/dev/null
  echo "" >> "$REPORT"

  # 5. Interval vector
  section "Interval Vector"
  # shellcheck disable=SC2086
  $S interval-vector $pcs >> "$REPORT" 2>/dev/null
  echo "" >> "$REPORT"

  # 6. Interval matrix (text)
  section "Interval Matrix"
  # shellcheck disable=SC2086
  $S interval-matrix $pcs >> "$REPORT" 2>/dev/null
  echo "" >> "$REPORT"

  # 7. Pitch-circle SVG
  # shellcheck disable=SC2086
  $S pitch-circle $pcs -o "$OUT_DIR/theory_ref_${slug}_circle.svg" 2>/dev/null

  # 8. Interval-matrix SVG
  # shellcheck disable=SC2086
  $S interval-matrix $pcs -o "$OUT_DIR/theory_ref_${slug}_matrix.svg" 2>/dev/null

done

# Summary table: collect Forte numbers for comparison
header "Summary: Forte Classifications"
printf "%-12s  %-14s  %s\n" "Chord" "Prime Form" "Forte" >> "$REPORT"
printf "%-12s  %-14s  %s\n" "-----" "----------" "-----" >> "$REPORT"
for entry in "${CHORDS[@]}"; do
  IFS='|' read -r symbol pcs slug <<< "$entry"
  # shellcheck disable=SC2086
  forte_out=$($S forte $pcs 2>/dev/null)
  pf=$(echo "$forte_out" | grep "Prime form:" | sed 's/.*: //')
  fn=$(echo "$forte_out" | grep "Forte:" | sed 's/.*: //')
  printf "%-12s  %-14s  %s\n" "$symbol" "$pf" "$fn" >> "$REPORT"
done
echo "" >> "$REPORT"

# Count outputs
n_svg=$(ls "$OUT_DIR"/theory_ref_*.svg 2>/dev/null | wc -l)
echo "Generated $n_svg SVG diagrams in $OUT_DIR/theory_ref_*.svg" >> "$REPORT"
echo "Full report: $REPORT" >> "$REPORT"

echo "Done. Report: $REPORT"
echo "SVG artifacts: $OUT_DIR/theory_ref_*.svg"
