#!/usr/bin/env bash
#
# Set-Class Explorer
#
# Demonstrates a comprehensive set-class exploration workflow: given a
# pitch-class set, compute its prime form, find its superchords (what
# larger structures contain it), enumerate its subchords (what smaller
# structures it contains), and generate visual diagrams.
#
# This exercises: prime-form, superchords, subchords, interval-vector,
# pitch-circle — combining text analysis with SVG output artifacts.
#
# Output:
#   - Text report: examples/output/explorer_report.txt
#   - SVG diagrams: examples/output/explorer_*.svg
#
# Usage:
#   bash slonimsky/examples/scripts/set_class_explorer.sh
#   SLONIMSKY=/path/to/slonimsky bash slonimsky/examples/scripts/set_class_explorer.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
OUT_DIR="$SCRIPT_DIR/../output"
mkdir -p "$OUT_DIR"

if [ -z "${SLONIMSKY:-}" ]; then
    SLONIMSKY="$(CARGO_HOME=/tmp/cargo-home cargo build -p slonimsky --message-format=short 2>&1 | tail -1)"
    SLONIMSKY="$SCRIPT_DIR/../../../target/debug/slonimsky"
fi

REPORT="$OUT_DIR/explorer_report.txt"
: > "$REPORT"

log() {
    echo "$@" | tee -a "$REPORT"
}

separator() {
    log ""
    log "$(printf '=%.0s' {1..60})"
    log ""
}

# Each entry: "label|pcs|description"
SETS=(
    "minor_triad|D F A|D minor triad — the relative minor of F major"
    "dom7sus4|C F G Bb|Dominant 7sus4 — ambiguous quartal/tonal structure"
    "octatonic_frag|C Db Eb E|Octatonic fragment — subset of the diminished scale"
    "pentatonic|C D E G A|Major pentatonic — the most universal scale"
    "tritone_pair|C E Gb Bb|Two interlocked tritones — French augmented 6th"
)

log "SET-CLASS EXPLORER REPORT"
log "========================="
log ""
log "Generated by slonimsky set-class explorer"
log "Date: $(date -u +%Y-%m-%d)"
log ""

for entry in "${SETS[@]}"; do
    IFS='|' read -r label pcs description <<< "$entry"

    separator
    log "## $description"
    log "   Input: $pcs"
    log ""

    # Prime form
    log "--- Prime Form ---"
    $SLONIMSKY prime-form $pcs -v 2>/dev/null | tee -a "$REPORT"
    log ""

    # Interval vector with labeled breakdown
    log "--- Interval Vector ---"
    $SLONIMSKY interval-vector $pcs 2>/dev/null | tee -a "$REPORT"
    log ""

    # Interval vector SVG
    $SLONIMSKY interval-vector $pcs \
        --title "IV: $description" \
        -o "$OUT_DIR/explorer_${label}_iv.svg" 2>/dev/null

    # Pitch-circle SVG
    $SLONIMSKY pitch-circle $pcs \
        --show-intervals \
        --title "$description" \
        -o "$OUT_DIR/explorer_${label}_circle.svg" 2>/dev/null

    # Superchords: what 4-note chords contain this set?
    pc_count=$(echo $pcs | wc -w)
    if [ "$pc_count" -lt 7 ]; then
        super_size=$((pc_count + 1))
        log "--- Superchords (size $super_size) ---"
        $SLONIMSKY superchords $pcs --min-size "$super_size" --max-size "$super_size" 2>/dev/null | tee -a "$REPORT"
        log ""
    fi

    # Subchords: what triads are inside this set?
    if [ "$pc_count" -ge 4 ]; then
        log "--- Subchords (size 3, named) ---"
        $SLONIMSKY subchords $pcs --size 3 --name 2>/dev/null | tee -a "$REPORT"
        log ""
    fi
done

separator
log "Report complete. $(ls "$OUT_DIR"/explorer_*.svg 2>/dev/null | wc -l) SVG diagrams generated."
log ""

echo ""
echo "Text report:  $REPORT"
echo "SVG diagrams: $OUT_DIR/explorer_*.svg"
