[package]
name = "musical-combinatorics"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
music = { path = "../music" }
anyhow = "1.0.66"
