// REQ-O19: errors via thiserror, matching `music` crate
// REQ-O17: TupletInexact for non-dividing ratios
// REQ-O15: TempoSourceEmpty for offline paths
// REQ-X10: SoundFontChecksum — never silent success on tampered cache

use thiserror::Error;

/// All errors that can be produced by `music-midi` conversion, playback, or rendering.
///
/// Every variant carries a human-readable message via its [`std::fmt::Display`] impl
/// (generated by `thiserror`). Do not match on the message string; match on the variant.
#[derive(Error, Debug)]
pub enum MidiConversionError {
    #[error("music-midi: pitch {0} is above MIDI range (max 127), clip or transpose before conversion")]
    PitchOutOfRange(u8),                                                 // REQ-O1

    #[error("music-midi: ppq {0} must be a multiple of 32, use 480 or 960")]
    InvalidPpq(u16),                                                     // REQ-O9, REQ-X7

    #[error("music-midi: tuplet {num}:{den} cannot be represented at ppq={ppq} without rounding, \
             increase ppq or accept ±1-tick quantization")]
    TupletInexact { num: u32, den: u32, ppq: u16 },                      // REQ-O17

    #[error("music-midi: score has {0} voices but MIDI allows at most 16 channels, split the score")]
    TooManyVoices(usize),                                                // REQ-O18

    #[error("music-midi: midly error: {0}, report upstream if reproducible")]
    Smf(String),                                                         // REQ-O8

    #[error("music-midi: I/O error: {0}")]
    Io(#[from] std::io::Error),

    #[error("music-midi: no realtime MIDI ports available, install fluidsynth or use the `render` feature")]
    NoPlaybackPort,                                                      // playback feature

    #[error("music-midi: soundfont load failed: {0}, verify the SF2 file is well-formed")]
    SoundFont(String),                                                   // REQ-O13

    #[error("music-midi: soundfont download failed: {0}, retry or use SoundFont::from_path")]
    SoundFontDownload(String),                                           // REQ-O13

    #[error("music-midi: soundfont checksum mismatch, expected {expected}, got {actual}, \
             delete cache and re-run")]
    SoundFontChecksum { expected: String, actual: String },              // REQ-X10

    #[error("music-midi: tempo source has no change points, offline export needs at least one, \
             use StaticTempoMap::constant(bpm) for fixed tempo")]
    TempoSourceEmpty,                                                    // REQ-O15, REQ-X9
}
